name: GitHub Actions eslint
run-name: ${{ github.actor }} is trying out eslint check

#if branches are not defined, it refers to all branches?
on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Installation via npm
        run: npm install
      - name: Run eslint
        run: |
          echo running branch ${{ github.head_ref || github.ref_name }} 
          npm run lint . --ext .js,.jsx,.ts,.tsx 
